### ISSUE TITLE
What's the maintenance status of redshift_sqlalchemy?

### ISSUE THREAD

**Issue by jklukas** [graingert/redshift_sqlalchemy#16]
It looks like all the action is happening in this fork rather than the original @binarydud repo. I'm working on a PR that fills out the reflection capabilities. Should I propose that here?

**Comment by graingert** [comment]
@jklukas yes please :)

**Comment by jklukas** [comment]
Will do. Is there a long-term plan for maintenance? Who's actively involved? We (@SimpleFinance) are going to be releasing a suite of Redshift maintenance tools in the future, with some bits depending on this SQLAlchemy dialect. We'd likely be willing to take on some role in maintenance on the project, and I want to make sure we'll be able to get new fixes pushed to PyPI in reasonable time.

**Comment by graingert** [comment]
@jklukas we can definitely talk about bringing a maintenance team together on this.

**Comment by graingert** [comment]
Closing this issue. The maintenance status of sqlalchemy-redshift is "maintained".
