### ISSUE TITLE
Hosted documentation

### ISSUE THREAD

**Issue by cpcloud** [graingert/redshift_sqlalchemy#25]
It'd be swell to have some documentation, that for now could consist of answers to questions like "How is this different from the postgresql dialect?" [rtfd.org](https://rtfd.org) + sphinx would be my tool of choice here, but others may have thoughts on this.

**Comment by jklukas** [comment]
+1 to hosted documentation, and the particulars of using sphinx and readthedocs. I can't think of any arguments for using a different stack for documentation.

**Comment by graingert** [comment]
Same here I definitely like rtfd and sphinx

**Comment by jklukas** [comment]
Starting this in https://github.com/graingert/redshift_sqlalchemy/pull/33
