### ISSUE TITLE
Redshift spinup/shutdown script

### ISSUE THREAD

**Issue by jklukas** [graingert/redshift_sqlalchemy#30]
We're running tests against Redshift now and have AWS access keys available to Travis, but the cluster is currently running full-time.

@graingert - you mentioned that you had a good idea of how to hook a script in to spin up the cluster for tests and then spin it back down. Are there any blockers at this point to make that happen?

**Comment by graingert** [comment]
No technical blockers, the current test script was just an MVP to get running quick

**Comment by graingert** [comment]
let's have a chat about this on IRC. We need a very locked down AWS that can only create/delete redshift instances, then it should be just some boto magic.

**Comment by jklukas** [comment]
I'm logged into freenode and on `#sqlalchemy` and will plan to be so for the rest of the day.

**Comment by graingert** [comment]
@jklukas I've started work on bigcrunch (it stops redshift, get it?)

https://github.com/graingert/bigcrunch/blob/master/bigcrunch/__main__.py

It's a heroku service, and at the moment it supports spinning up the service, adding a test session, and removing tests sessions when they are done.

Not implemented is shutting down the server on an hourly job when there are no unexpired sessions.

**Comment by jklukas** [comment]
Just a note that Bigcrunch seems to be doing its job. I was just looking at AWS billing, and we've only used $3.50 worth of Redshift so far this month. :+1:

**Comment by graingert** [comment]
woop woop, it's a bit glitchy and there's some really obvious error handling I need to insert. But I'm happy restarting the build if you are!
