### ISSUE TITLE
Reflection should raise the proper Exception type when things are not found

### ISSUE THREAD

**Issue by cpcloud** [graingert/redshift_sqlalchemy#38]
Right now, when reflection fails, it's usually with a `KeyError`, but the other sqlalchemy dialects raise `sa.exc.NoSuch<object>Error`. I have code that depends on this exception being raised, which is how I found this issue.

I've got a PR in the works.

**Comment by cpcloud** [comment]
This was introduced in 1b911f2

**Comment by cpcloud** [comment]
It looks like only `sa.exc.NoSuchTableError` is relevant during reflection

**Comment by graingert** [comment]
Ah nice catch! Do you have the docs for this?

**Comment by cpcloud** [comment]
There's the docs for the exception: http://docs.sqlalchemy.org/en/rel_1_0/core/exceptions.html?highlight=nosuchtableerror#sqlalchemy.exc.NoSuchTableError

I'm looking for the usage docs (if any) right now.

**Comment by cpcloud** [comment]
I don't see anything here explicitly stating what exceptions should be raised in the case of not finding tables: http://docs.sqlalchemy.org/en/rel_1_0/core/reflection.html

I grepped through sqlalchemy core and found that indeed sybase, postgresql, and mysql all raise `NoSuchTableError` for specific functions (postgres has a `get_table_oid` method that raises it, mysql raises when doing a `show create table` or `describe mytable` statements, sybase has a similar mechanism to postgres).

For other dialects I think the error is raised here (in the `Inspector` class):

https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/engine/reflection.py#L570-L571
