### ISSUE TITLE
Run travis tests on real redshift database

### ISSUE THREAD

**Issue by graingert** [graingert/redshift_sqlalchemy#9]
Can't currently justify the cost of a redshift database just to run travis tests.

**Comment by adamchainz** [comment]
Is this possible via Travis? Wouldn't you really need an EC2 test pipeline?

**Comment by graingert** [comment]
I'd just create a public redshift database and keep the password encrypted in my .travis.yml

**Comment by adamchainz** [comment]
:moneybag:

**Comment by jklukas** [comment]
This is happening. I've stood up a basic single-node cluster at `redshift-sqlalchemy-test.cforsfjmjsja.us-west-2.redshift.amazonaws.com:5439` and created `klukas`, `graingert`, and `travis` accounts both for IAM users and for Redshift users.

The IAM accounts all have the "AmazonRedshiftFullAccess" policy attached, so should be able to shutdown and launch the cluster as needed.

The Redshift users are members of a `testers` group, which has `CREATE` access on the `public` and `test` schemas.

@graingert: Do you have a GPG key I could use to encrypt creds? Let me know if you have other thoughts about how to transmit. Would you be willing to give me Travis access, assuming that's necessary for uploading creds there?

Should we wait on implementing this until https://github.com/zzzeek/sqlalchemy/pull/196 gets sorted? I don't know what the thoughts are right now on updating @binarydud's version. Perhaps there would be benefit to moving this to a `redshift_sqlalchemy` org?

**Comment by graingert** [comment]
@jklukas you can just use the travis encrypt instructions at http://docs.travis-ci.com/user/encryption-keys/

**Comment by graingert** [comment]
I never have to know the password :D

**Comment by graingert** [comment]
https://api.travis-ci.org/graingert/redshift_sqlalchemy/key

**Comment by graingert** [comment]
Some example for pytest fixtures:

```python
# -*- encoding:utf-8 -*-
from __future__ import absolute_import, division, unicode_literals

import copy
import contextlib
import itertools
import uuid

from alembic import command, config
import pytest

from somewhere import db
from somewhere import configuration


def database_name_generator():
    template = 'testdb_{uuid}_{count}'
    db_uuid = unicode(uuid.uuid1()).replace('-', '')
    for i in itertools.count():
        yield template.format(
            uuid=db_uuid,
            count=i,
        )

database_name = database_name_generator().next


class DatabaseTool(object):
    """
    Abstracts the creation and destruction of migrated databases.
    """
    def __init__(self):
        self.engine = self.engine_definition.engine()

    @contextlib.contextmanager
    def _database(self):
        db_name = database_name()
        with self.engine.connect() as conn:
            conn.execute('COMMIT')  # Can't create databases in a transaction
            conn.execute('CREATE DATABASE {db_name}'.format(db_name=db_name))

        dburl = copy.deepcopy(self.engine.url)
        dburl.database = db_name

        try:
            yield db.EngineDefinition(
                db_connect_url=dburl,
                connect_args=self.engine_definition.connect_args,
                poolclass=self.engine_definition.poolclass,
            )
        finally:
            with self.engine.connect() as conn:
                conn.execute('COMMIT')  # Can't drop databases in a transaction
                conn.execute('DROP DATABASE {db_name}'.format(db_name=db_name))

    @contextlib.contextmanager
    def migrated_database(self):
        """
        Test fixture for testing real commits/rollbacks.

        Creates and migrates a fresh database for every test.
        """
        with self._database() as engine_definition:
            engine = engine_definition.engine()
            try:
                self.migrate(engine)
                yield {
                    'definition': engine_definition,
                    'engine': engine,
                }
            finally:
                engine.dispose()

    def migrate(self, engine):
        alembic_cfg = config.Config()
        alembic_cfg.set_main_option(
            'script_location',
            self.migration_script_location,
        )
        with engine.begin() as connection:
            alembic_cfg.attributes['connection'] = connection
            command.upgrade(alembic_cfg, 'head')


class RedshiftDatabaseTool(DatabaseTool):
    migration_script_location = 'datascience.alembic:redshift'
    engine_definition = db.EngineDefinition.from_config(
        configuration.config['redshift_testing'],
        'redshift+psycopg2',
    )


redshift_database_tool = RedshiftDatabaseTool()


@pytest.yield_fixture(scope='function')
def _redshift_engine_and_definition():
    with redshift_database_tool.migrated_database() as database:
        yield database


@pytest.fixture(scope='function')
def redshift_engine(_redshift_engine_and_definition):
    """
    A redshift engine for a freshly migrated database.
    """
    return _redshift_engine_and_definition['engine']


@pytest.fixture(scope='function')
def redshift_engine_definition(_redshift_engine_and_definition):
    """
    A redshift engine definition for a freshly migrated database.
    """
    return _redshift_engine_and_definition['definition']


@pytest.yield_fixture(scope='session')
def _session_scoped_redshift_engine():
    """
    Private fixture to maintain a db for the entire test session.
    """
    with redshift_database_tool.migrated_database() as egs:
        yield egs['engine']


@pytest.yield_fixture(scope='function')
def redshift_session(_session_scoped_redshift_engine):
    """
    A redshift session that rolls back all operations.

    The engine and db is maintained for the entire test session for efficiency.
    """
    conn = _session_scoped_redshift_engine.connect()
    tx = conn.begin()
    session = db.RedshiftSession(bind=conn)
    try:
        yield session
    finally:
        session.close()
        tx.rollback()
        conn.close()
```

**Comment by graingert** [comment]
https://github.com/sqlalchemy-redshift

**Comment by graingert** [comment]
To be able to work in parallel `travis` will also need create/drop privileges

**Comment by graingert** [comment]
My plan for the lifetime of the cluster is a single schema with a single table with a single column.

Pseudo code:

* idem-potently boot redshift cluster
* test_sess = uuid.uuid4()
*  "INSERT INTO test_sessions (test_session,)
   VALUES (:uuid)".params(uuid=test_sess)
* run tests
* "DELETE FROM test_sessions WHERE uuid=:uuid".params(uuid=test_sess)
* if not "EXISTS SELECT * FROM test_sessions":
    * Shutdown cluster.

**Comment by jklukas** [comment]
Is @binarydud cool with the idea of transferring ownership to https://github.com/sqlalchemy-redshift?

**Comment by jklukas** [comment]
@graingert: It looks like you have a good handle on the structure we should be using for running tests against the real Redshift environment, but I'm not quite sure how to take your example code and actually run tests from it. Would you be willing to start a branch that sets up the fixture and gives an example test using the database? I can incorporate that back in and build test for #17 on it.

**Comment by jklukas** [comment]
I added a `.travis.yml` clause that puts a relevant `PGPASSWORD` to the environment to go along with the `travis` Redshift user: https://github.com/graingert/redshift_sqlalchemy/commit/3da0832096543957c16df9d788217466f08edafc

**Comment by graingert** [comment]
Can do, if you want to have a stab at it in the meantime if you can't wait
for me you can have a look at https://pytest.org/latest/fixture.html for
how to use my example code

**Comment by graingert** [comment]
Fixed in https://github.com/graingert/redshift_sqlalchemy/pull/19
